#!/bin/sh

base=$(dirname $(readlink -f $0))

source $base/scripts/vin-tests.sh
source $base/scripts/boards.sh

$base/gen3-links.sh

out=/tmp/vin-tests
rm -fr $out
mkdir -p $out

mdev=$(mc_get_mdev)
src="'$hdminame':1"
size=$($mediactl -d $mdev --get-v4l2 "$src" | sed 's|.*fmt:[^/]*/\([^ ]*\).*|\1|')

yavta -n 4 --capture=10 /dev/$vin0 --file=$out/frame-#.bin $*

strings $out/frame*.bin | head | wc -l
md5sum $out/frame*.bin
for f in $out/frame*.bin ; do $base/convert.sh $f $size ; done;
