#!/bin/sh

set -e

base=$(dirname $(readlink -f $0))

source $base/scripts/vin-tests.sh
source $base/scripts/boards.sh

vc=0
if [[ $# -eq 1 ]]; then
    vc=$1
fi

case $vc in
    0)
        vinname=$vinname0
        dev=/dev/$vin0
        csipad=1
        ;;
    1)
        vinname=$vinname1
        dev=/dev/$vin1
        csipad=2
        ;;
    2)
        vinname=$vinname2
        dev=/dev/$vin2
        csipad=3
        ;;
    3)
        vinname=$vinname3
        dev=/dev/$vin3
        csipad=4
        ;;
    4)
        vinname=$vinname4
        dev=/dev/$vin4
        csipad=1
        ;;
    5)
        vinname=$vinname5
        dev=/dev/$vin5
        csipad=2
        ;;
    *)
        echo "Unkown VC '$vc'"
        exit 1
esac

mc_reset
mc_propagate_hdmi "$vinname" $csipad

out=/tmp/vin-tests
rm -fr $out
mkdir -p $out

size=$(v4l2-ctl --all -d $dev  | awk '/Width/{print $3}' | tr '/' 'x')

yavta -n 4 --capture=10 $dev --file=$out/frame-#.bin $*

strings $out/frame*.bin | head | wc -l
md5sum $out/frame*.bin
for f in $out/frame*.bin ; do $base/convert.sh $f $size ; done;
